name: personal-website
services:
  frontend:
    build:
      context: frontend
    networks:
      - client-side
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: backend
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8000:8000'
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend:/app
      - backend-cache:/app/target
    command: bash -c "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - server-side
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data


networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
